# Grant permission to create deployments to user 'lambda'
# Usage: kubectl apply -f permissions.yml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-create-deployments
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-create-deployments
  namespace: default
subjects:
  - kind: User
    name: lambda
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: lambda-create-deployments
  apiGroup: rbac.authorization.k8s.io
